### ISSUE TITLE
entrypoint does not check for the right env var before importing certs

### ISSUE THREAD

**Issue by sami-alajrami** [Praqma/jira-server#8]
this line https://github.com/Praqma/jira-server/blob/bb99b4cd6d81c8b06211397caffb0da708c86a00/docker-entrypoint.sh#L204

doesn't check the correct env var before importing certs!
Importing certs should happen ONLY if `ENABLE_CERT_IMPORT` is set to true. This is passed from the helm chart.

And what are these two env vars and where are they coming from : SSL_CERTS_DIR .. CERTIFICATE?

**Comment by hoeghh** [comment]
I have a customer that needs this today if possible.
Whats the chance of that?

**Comment by sheeeng** [comment]
Working on it. @hoeghh

**Comment by sheeeng** [comment]
@hoeghh, please test `praqma/jira-server:7.8.2-v1` container image for this issue.
